import 'package:uuid/uuid.dart';

import '../../../ai_layer/models/ai_response.dart';
import '../../../core/constants/firebase_collections.dart';
import '../../../core/enums/app_enums.dart';
import '../data/message_dto.dart';

const _unset = Object();

/// Immutable entity representing a single message in a conversation.
///
/// In Firestore, messages are stored as prompt+response pairs:
///   AI_Voice_Genie/AI_Conversations/{uid}/{conversationId}/messages/{messageId}
///   Each document contains both the user prompt and AI response.
///
/// In the UI, each pair is split back into two MessageModel instances
/// (one user, one assistant) for display in the chat list.
///
/// Supports all content types: text, image URL, PDF summary, voice transcript.
class MessageModel {
  /// Unique identifier of the message turn (UUID v4).
  ///
  /// Used for:
  /// - Unique key in UI list rendering ([ListView] keys).
  /// - Document ID mapping in Firestore (`messages/{messageId}`).
  /// - Hive storage key generation (`{uid}_{conversationId}_{messageId}`).
  /// - Optimistic UI matching when remote updates arrive.
  final String messageId;

  /// Sender role: [MessageRole.user] for user prompts, [MessageRole.assistant] for AI responses.
  ///
  /// Used for:
  /// - UI bubble alignment (right for user, left for assistant).
  /// - Bubble theme styling (accent color for user, card surface for assistant).
  /// - Distinguishing `prompt` vs `response` serialization keys in Firestore/Hive.
  /// - Multi-turn conversational context construction in LLM adapters.
  final MessageRole role;

  /// Primary textual content of the message turn.
  ///
  /// Used for:
  /// - User turn: The input prompt, question, or multimodal caption submitted to the AI.
  /// - Assistant turn: The completed response generated by the LLM.
  /// - Failed turn: When [status] is [MessageStatus.failed], carries the user-facing localized failure message.
  /// - Direct display in chat bubble UI markdown widgets.
  final String lastPrompt;

  /// The active AI capability modality for this message turn.
  ///
  /// Used for:
  /// - Directing which UI bubble type to render (plain text markdown, image carousel, or PDF card).
  /// - Selecting the appropriate serialization field (`request_capability` vs `response_capability`).
  /// - Validating provider feature support before executing request pipelines.
  final AiCapability requestCapability;

  /// The timestamp indicating when the message was originally created locally.
  ///
  /// Used for:
  /// - Chronological ordering in chat conversations (oldest first).
  /// - Date separator headers in the UI ("Today", "Yesterday", specific dates).
  /// - Pagination cursor tracking ([MessagePageCursor]).
  final DateTime timestamp;

  /// The specific AI provider (model engine) targeted or used for this message turn.
  ///
  /// Used for:
  /// - Rendering the provider badge (e.g., Gemini, OpenAI, Claude) on assistant bubbles.
  /// - Route selection in [AiOrchestrator] and fallback tracking.
  /// - Storing `modelUsed` in Firestore and Hive.
  final AiProviderId? modelRequest;

  /// Total token count consumed by this generation turn (prompt + completion tokens).
  ///
  /// Used for:
  /// - Storing `tokenCount` in Firestore and Hive on assistant responses.
  /// - Tracking per-user and per-provider quota/budget utilization.
  /// - Omitted on user prompt messages.
  final int tokenCount;

  /// Lifecycle delivery status of this message:
  /// - [MessageStatus.sending]: In-flight optimistic message awaiting completion.
  /// - [MessageStatus.delivered]: Successfully completed and persisted turn.
  /// - [MessageStatus.failed]: Request failed after retries/fallbacks exhausted.
  /// - [MessageStatus.partial]: Streaming response in progress.
  ///
  /// Used for:
  /// - Showing loading spinner / delivery checks / retry action buttons in UI bubbles.
  /// - Distinguishing successful delivered messages from failed attempts (where [lastPrompt] carries the failure explanation).
  final MessageStatus status;

  /// Latency in milliseconds from request dispatch to final response completion.
  ///
  /// Used for:
  /// - Assistant responses only; omitted for user messages.
  /// - Telemetry, performance monitoring, and analytics tracking.
  final int? responseTimeMs;

  /// Provider stop reason indicating why generation halted (e.g., 'STOP', 'length', 'safety').
  ///
  /// Used for:
  /// - Assistant responses only.
  /// - Detecting truncated output or safety filter triggers.
  /// - Persisted in Firestore and Hive when non-empty.
  final String? finishReason;

  /// The originating request ID correlating this response turn to the prompt turn that created it.
  ///
  /// Used for:
  /// - Assistant turns: References the user prompt's [messageId].
  /// - Persisted in Firestore and Hive under `requestId`.
  final String? requestId;

  /// Cloud Storage URLs or local image file paths attached to this message.
  ///
  /// Used for:
  /// - User turn: Photos uploaded for vision analysis ([AiCapability.imageUnderstanding]).
  /// - Assistant turn: Downloadable image URLs generated by [AiCapability.imageGeneration].
  final List<String>? imageUrls;

  /// Structured PDF attachments metadata ([PdfAttachmentInfo]).
  ///
  /// Used for:
  /// - Storing and displaying local file paths, file sizes, document names, and Cloud Storage URLs.
  /// - Rendering interactive PDF document cards in chat bubbles.
  final List<PdfAttachmentInfo>? pdfInfo;

  /// In-memory transient flag indicating an optimistic message inserted before server confirmation.
  ///
  /// Used for:
  /// - Immediate UI responsiveness without waiting for round-trip network latency.
  /// - Never written to Firestore or Hive.
  final bool isOptimistic;

  /// Requested aspect ratio / resolution for image generation ([AiCapability.imageGeneration]).
  ///
  /// Used for:
  /// - Configuring image dimensions for Gemini (1:1, 16:9, 9:16) and OpenAI (1024x1024, etc.).
  /// - Persisted in Firestore and Hive under `imageSize`.
  final AiImageSize? imageSize;

  /// Number of images requested in an image generation prompt.
  ///
  /// Used for:
  /// - Specifying image batch count (e.g. 1 to 4 images).
  /// - Persisted in Firestore and Hive under `imageCount`.
  final int? generateImageRequest;

  /// Quality tier for generated images (e.g. [ImageQuality.standard] vs [ImageQuality.hd]).
  ///
  /// Used for:
  /// - OpenAI DALL-E 3 image generation.
  /// - Omitted for Gemini and persisted under `imageQuality`.
  final ImageQuality? imageQuality;

  /// Requested background aesthetic for generated images (e.g. transparent, white, studio).
  ///
  /// Used for:
  /// - OpenAI image generation styling.
  /// - Persisted in Firestore and Hive under `imageBackground`.
  final ImageGenerateBackground? imageBackground;

  /// Fidelity detail level for vision understanding requests ([VisionDetailLevel.low], [VisionDetailLevel.high]).
  ///
  /// Used for:
  /// - Controlling OpenAI GPT-4o vision image sampling resolution and token costs.
  /// - Persisted in Firestore and Hive under `visionDetailLevel`.
  final VisionDetailLevel? visionDetailLevel;

  /// User's preferred AI response length tier (e.g. short, balanced, detailed, maximum).
  ///
  /// Used for:
  /// - Recording the length tier requested by the user.
  /// - Persisted in Firestore and Hive under `responseLength`.
  final ResponseLength? responseLength;

  /// User's preferred reasoning thinking depth for Gemini models (e.g. low, medium, high).
  ///
  /// Used for:
  /// - Recording reasoning budget requested for Gemini text generation.
  /// - Persisted in Firestore and Hive under `thinkingLevel`.
  final GeminiThinkingLevel? thinkingLevel;

  /// Explicit maximum output tokens calculated for the selected provider.
  ///
  /// Used for:
  /// - Recording the exact token ceiling enforced on the model.
  /// - Persisted in Firestore and Hive under `maxOutputTokens`.
  final int? maxOutputTokens;

  /// Formatted image size / aspect ratio string for Firestore and Hive persistence.
  ///
  /// Translates internal enum values into standardized provider strings:
  /// - Gemini: "Square (1:1)", "Landscape (16:9)", "Portrait (9:16)"
  /// - OpenAI: "Square", "Landscape", "Portrait"
  String? get effectiveImageSizeString {
    if (imageSize == null) return null;
    if (modelRequest == AiProviderId.gemini) {
      switch (imageSize!) {
        case AiImageSize.landscape:
          return 'Landscape (16:9)';
        case AiImageSize.portrait:
          return 'Portrait (9:16)';
        case AiImageSize.square:
          return 'Square (1:1)';
      }
    }
    return imageSize!.name;
  }

  /// Standard constructor for [MessageModel].
  MessageModel({
    required this.lastPrompt,
    required this.modelRequest,
    required this.requestCapability,
    this.status = MessageStatus.partial,
    this.isOptimistic = false,
    this.role = MessageRole.assistant,
    this.tokenCount = 0,
    this.responseTimeMs,
    this.finishReason,
    this.requestId,
    this.imageUrls,
    this.pdfInfo,
    this.imageSize,
    this.generateImageRequest,
    this.imageQuality,
    this.imageBackground,
    this.visionDetailLevel,
    this.responseLength,
    this.thinkingLevel,
    this.maxOutputTokens,
    DateTime? timestamp,
    String? msgId,
  })  : messageId = msgId ?? const Uuid().v4(),
        timestamp = timestamp ?? DateTime.now();

  /// Factory constructor to build a new optimistic user prompt message.
  ///
  /// Used to instantly render the user's message in the UI before dispatching to the network.
  factory MessageModel.userMessage({
    required String lastPrompt,
    required AiProviderId provider,
    required AiCapability requestCapability,
    List<String>? imagePaths,
    List<PdfAttachmentInfo>? pdfInfo,
    AiImageSize? imageSize,
    int? generateImageRequest,
    ImageQuality? imageQuality,
    ImageGenerateBackground? imageBackground,
    VisionDetailLevel? visionDetailLevel,
    ResponseLength? responseLength,
    GeminiThinkingLevel? thinkingLevel,
    int? maxOutputTokens,
  }) {
    return MessageModel(
      lastPrompt: lastPrompt,
      modelRequest: provider,
      requestCapability: requestCapability,
      status: MessageStatus.sending,
      isOptimistic: true,
      role: MessageRole.user,
      imageUrls: imagePaths,
      pdfInfo: pdfInfo,
      imageSize: imageSize,
      generateImageRequest: generateImageRequest,
      imageQuality: imageQuality,
      imageBackground: imageBackground,
      visionDetailLevel: visionDetailLevel,
      responseLength: responseLength,
      thinkingLevel: thinkingLevel,
      maxOutputTokens: maxOutputTokens,
    );
  }

  /// Factory constructor to build a [MessageModel] directly from an [AiResponse].
  ///
  /// Maps unified [AiResponse] fields (responseId, text, modelUsed, tokens, latency, finishReason)
  /// directly into a domain [MessageModel] without requiring capability switch boilerplate.
  factory MessageModel.fromAiResponse(
    AiResponse response, {
    List<String>? imageUrls,
    List<PdfAttachmentInfo>? pdfInfo,
    MessageStatus status = MessageStatus.delivered,
    AiImageSize? imageSize,
    int? generateImageRequest,
    ImageQuality? imageQuality,
    ImageGenerateBackground? imageBackground,
  }) {
    final bool isPdf = response.capability == AiCapability.pdfGeneration;
    final String promptText = (isPdf && pdfInfo != null && pdfInfo.isNotEmpty)
        ? 'Here is the required PDF as you requested.'
        : (response.text ?? '');

    // If explicit imageUrls are provided, use them.
    // Otherwise, automatically derive instant base64 data-URIs from response.imagesBase64
    // so image generation results render immediately without requiring pre-uploaded URLs.
    final List<String>? effectiveImages = (imageUrls != null &&
            imageUrls.isNotEmpty)
        ? imageUrls
        : (response.imagesBase64 != null && response.imagesBase64!.isNotEmpty)
            ? response.imagesBase64!.map((raw) {
                if (raw.startsWith('data:image') ||
                    raw.startsWith('http://') ||
                    raw.startsWith('https://')) {
                  return raw;
                }
                final mime =
                    raw.startsWith('/9j/') ? 'image/jpeg' : 'image/png';
                return 'data:$mime;base64,$raw';
              }).toList()
            : null;

    return MessageModel(
      msgId: response.responseId,
      requestId: response.requestId,
      lastPrompt: promptText,
      modelRequest: response.modelUsed,
      requestCapability: response.capability,
      finishReason: response.finishReason ?? 'Fail',
      role: MessageRole.assistant,
      status: status,
      tokenCount: response.tokenCount,
      responseTimeMs: response.responseTimeMs,
      imageUrls: effectiveImages,
      pdfInfo: pdfInfo,
      isOptimistic: false,
      imageSize: imageSize,
      generateImageRequest: generateImageRequest ??
          (effectiveImages != null && effectiveImages.isNotEmpty
              ? effectiveImages.length
              : null),
      imageQuality: imageQuality,
      imageBackground: imageBackground,
    );
  }

  /// Deserializes a [MessageModel] from a Firestore document snapshot.
  /// Uses [MessageDto] for resilient multi-key decoding and safe type parsing.
  factory MessageModel.fromFirestore(String id, Map<String, dynamic> data) {
    final effectiveData = Map<dynamic, dynamic>.from(data);
    effectiveData[FirebaseCollections.fieldMessageID] = id;
    return MessageDto.fromMap(effectiveData).toDomain();
  }

  /// Alias for [messageId] to maintain seamless compatibility.
  String get id => messageId;

  /// Convenience getter indicating if the message originated from the human user.
  bool get isUser => role == MessageRole.user;

  /// Serializes the message model for storage in Firestore via [MessageDto].
  Map<String, dynamic> toFirestore() =>
      MessageDto.fromDomain(this).toFirestoreMap();

  /// Serializes the message model for outbox payload (Firestore sync) via [MessageDto].
  Map<String, dynamic> toSyncPayload() =>
      MessageDto.fromDomain(this).toSyncPayload();

  /// Serializes the message model for local Hive / JSON cache via [MessageDto].
  Map<String, dynamic> toCacheMap() => MessageDto.fromDomain(this).toCacheMap();

  /// Deserializes a [MessageModel] from local Hive / JSON cache via [MessageDto].
  factory MessageModel.fromCacheMap(Map<String, dynamic> data) =>
      MessageDto.fromMap(data).toDomain();

  /// Converts the message model to a standard map entry suitable for conveying
  /// chat history context to standard AI provider APIs (OpenAI, Gemini, Claude).
  ///
  /// Intelligently represents user attachments (images, PDFs) and AI-generated
  /// media (images, PDFs) so the LLM retains complete context of prior turns
  /// even when messages contain media instead of plain text.
  Map<String, String> toHistoryEntry() {
    String resolvedContent = lastPrompt.trim();

    // 1. Failed messages
    if (status == MessageStatus.failed) {
      return {
        'role': role.value,
        'content':
            '[The previous response encountered a temporary error and could not complete.]',
      };
    }

    // 2. User messages with attachments
    if (role == MessageRole.user) {
      if (pdfInfo != null && pdfInfo!.isNotEmpty) {
        final names =
            pdfInfo!.map((p) => p.name).where((n) => n.isNotEmpty).join(', ');
        final label = names.isNotEmpty
            ? '[Attached PDF: $names]'
            : '[Attached PDF document]';
        resolvedContent =
            resolvedContent.isNotEmpty ? '$label $resolvedContent' : label;
      } else if (imageUrls != null && imageUrls!.isNotEmpty) {
        final count = imageUrls!.length;
        final label =
            count > 1 ? '[Attached $count images]' : '[Attached image]';
        resolvedContent =
            resolvedContent.isNotEmpty ? '$label $resolvedContent' : label;
      }
    }

    // 3. Assistant messages with generated media
    if (role == MessageRole.assistant) {
      if (requestCapability == AiCapability.pdfGeneration ||
          (pdfInfo != null && pdfInfo!.isNotEmpty)) {
        final docName = pdfInfo?.firstOrNull?.name;
        final label = docName != null && docName.isNotEmpty
            ? '[Generated PDF document: $docName]'
            : '[Generated PDF document]';
        resolvedContent = resolvedContent.isNotEmpty && resolvedContent != label
            ? '$label $resolvedContent'
            : label;
      } else if (requestCapability == AiCapability.imageGeneration ||
          (imageUrls != null && imageUrls!.isNotEmpty)) {
        final count = imageUrls?.length ?? 1;
        final label =
            count > 1 ? '[Generated $count images]' : '[Generated image]';
        resolvedContent =
            resolvedContent.isNotEmpty ? '$resolvedContent $label' : label;
      }
    }

    // Fallback if completely empty
    if (resolvedContent.isEmpty) {
      resolvedContent =
          role == MessageRole.user ? '[User message]' : '[Assistant response]';
    }

    return {
      'role': role.value,
      'content': resolvedContent,
    };
  }

  /// Creates a copy of this message model with the given fields replaced.
  MessageModel copyWith({
    String? id,
    MessageRole? role,
    String? prompt,
    AiCapability? contentType,
    DateTime? timestamp,
    Object? modelUsed = _unset,
    int? tokenCount,
    MessageStatus? status,
    Object? responseTimeMs = _unset,
    Object? finishReason = _unset,
    Object? requestId = _unset,
    Object? imageUrls = _unset,
    Object? pdfInfo = _unset,
    bool? isOptimistic,
    Object? imageSize = _unset,
    Object? generateImageRequest = _unset,
    Object? imageQuality = _unset,
    Object? imageBackground = _unset,
    Object? visionDetailLevel = _unset,
    Object? responseLength = _unset,
    Object? thinkingLevel = _unset,
    Object? maxOutputTokens = _unset,
  }) {
    return MessageModel(
      msgId: id ?? messageId,
      role: role ?? this.role,
      lastPrompt: prompt ?? lastPrompt,
      requestCapability: contentType ?? requestCapability,
      timestamp: timestamp ?? this.timestamp,
      modelRequest: identical(modelUsed, _unset)
          ? modelRequest
          : modelUsed as AiProviderId?,
      tokenCount: tokenCount ?? this.tokenCount,
      status: status ?? this.status,
      responseTimeMs: identical(responseTimeMs, _unset)
          ? this.responseTimeMs
          : responseTimeMs as int?,
      finishReason: identical(finishReason, _unset)
          ? this.finishReason
          : finishReason as String?,
      requestId:
          identical(requestId, _unset) ? this.requestId : requestId as String?,
      imageUrls: identical(imageUrls, _unset)
          ? this.imageUrls
          : imageUrls as List<String>?,
      pdfInfo: identical(pdfInfo, _unset)
          ? this.pdfInfo
          : pdfInfo as List<PdfAttachmentInfo>?,
      isOptimistic: isOptimistic ?? this.isOptimistic,
      imageSize: identical(imageSize, _unset)
          ? this.imageSize
          : imageSize as AiImageSize?,
      generateImageRequest: identical(generateImageRequest, _unset)
          ? this.generateImageRequest
          : generateImageRequest as int?,
      imageQuality: identical(imageQuality, _unset)
          ? this.imageQuality
          : imageQuality as ImageQuality?,
      imageBackground: identical(imageBackground, _unset)
          ? this.imageBackground
          : imageBackground as ImageGenerateBackground?,
      visionDetailLevel: identical(visionDetailLevel, _unset)
          ? this.visionDetailLevel
          : visionDetailLevel as VisionDetailLevel?,
      responseLength: identical(responseLength, _unset)
          ? this.responseLength
          : responseLength as ResponseLength?,
      thinkingLevel: identical(thinkingLevel, _unset)
          ? this.thinkingLevel
          : thinkingLevel as GeminiThinkingLevel?,
      maxOutputTokens: identical(maxOutputTokens, _unset)
          ? this.maxOutputTokens
          : maxOutputTokens as int?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageModel &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId;

  @override
  int get hashCode => messageId.hashCode;

  @override
  String toString() => 'MessageModel(id: $messageId, role: ${role.value}, '
      'requestId: $requestId, status: ${status.value})';
}

/// Immutable class representing combined PDF attachment path, cloud URL, and name.
class PdfAttachmentInfo {
  final String path;
  final String name;
  final int? fileSizeBytes;
  final String? url;

  const PdfAttachmentInfo({
    required this.path,
    required this.name,
    this.fileSizeBytes,
    this.url,
  });

  factory PdfAttachmentInfo.fromMap(Map<String, dynamic> map) {
    final rawPath = map['path'] as String? ?? '';
    final rawUrl = map['url'] as String?;
    return PdfAttachmentInfo(
      path: rawPath,
      name: map['name'] as String? ?? '',
      fileSizeBytes: map['fileSizeBytes'] as int?,
      url: rawUrl ?? (rawPath.startsWith('http') ? rawPath : null),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'path': path,
      'name': name,
      if (fileSizeBytes != null) 'fileSizeBytes': fileSizeBytes,
      if (url != null) 'url': url,
    };
  }

  PdfAttachmentInfo copyWith({
    String? path,
    String? name,
    int? fileSizeBytes,
    String? url,
  }) {
    return PdfAttachmentInfo(
      path: path ?? this.path,
      name: name ?? this.name,
      fileSizeBytes: fileSizeBytes ?? this.fileSizeBytes,
      url: url ?? this.url,
    );
  }

  String get fileSizeLabel {
    if (fileSizeBytes == null) return '';
    if (fileSizeBytes! >= 1000 * 1000) {
      return '${(fileSizeBytes! / (1000 * 1000)).toStringAsFixed(1)} MB';
    }
    return '${(fileSizeBytes! / 1000).toStringAsFixed(0)} KB';
  }

  @override
  String toString() =>
      'PdfAttachmentInfo(name: $name, path: $path, size: $fileSizeBytes, url: $url)';
}
