import 'package:uuid/uuid.dart';

import '../../core/enums/app_enums.dart';

/// Unified response object returned by [AiOrchestrator.execute].
///
/// Regardless of which provider handled the request, the caller
/// always receives an [AiResponse] with the same normalized shape.
class AiResponse {
  // ── Always Present ─────────────────────────────────────────────────────────

  /// The unique message ID generated dynamically for this AI response turn (UUID v4).
  final String responseId;

  /// Which AI provider ultimately fulfilled this request (e.g., Gemini, OpenAI, Claude).
  final AiProviderId modelUsed;

  /// The active AI capability modality executed (e.g., textGeneration, imageGeneration, pdfGeneration).
  final AiCapability capability;

  /// The original request ID correlating this response turn to the prompt turn that created it.
  final String requestId;

  /// How long the provider took to respond in milliseconds (network round-trip latency).
  final int responseTimeMs;

  // ── Payload Content ────────────────────────────────────────────────────────

  /// Text content — populated for textGeneration, imageUnderstanding, pdfParsing, and pdfGeneration.
  final String? text;

  /// Base64-encoded image string(s) returned by the AI provider for imageGeneration.
  final List<String>? generatedImages;

  // ── Usage Metadata ─────────────────────────────────────────────────────────

  /// Input/prompt tokens consumed by this generation turn.
  final int inputTokens;

  /// Output/completion tokens generated by this generation turn.
  final int outputTokens;

  /// Total tokens consumed (inputTokens + outputTokens).
  final int tokenCount;

  /// Stop reason from the model engine (e.g., 'STOP', 'length', 'content_filter').
  final String? finishReason;

  /// Unified constructor for [AiResponse].
  ///
  /// Image Normalization Flow:
  /// Adapters pass a list of base64 strings or a single base64 string.
  /// All are normalized into the primary [generatedImages] list.
  AiResponse({
    required this.requestId,
    required this.modelUsed,
    required this.capability,
    required this.responseTimeMs,
    this.text,
    this.generatedImages,
    this.inputTokens = 0,
    this.outputTokens = 0,
    this.tokenCount = 0,
    this.finishReason = 'Fail',
    String? responseId,
  }) : responseId = (responseId != null && responseId.isNotEmpty)
            ? responseId
            : const Uuid().v4();

  // ── Named Constructors ─────────────────────────────────────────────────────

  /// Creates a text-based response (used for textGeneration, pdfParsing, imageUnderstanding, and pdfGeneration).
  ///
  /// Automatically computes [tokenCount] as (inputTokens + outputTokens) if [tokenCount] is not explicitly supplied.
  factory AiResponse.text({
    required String requestId,
    required AiProviderId modelUsed,
    required AiCapability capability,
    required int responseTimeMs,
    required String text,
    int inputTokens = 0,
    int outputTokens = 0,
    int tokenCount = 0,
    String? finishReason = 'Fail',
    String? responseId,
  }) {
    final int resolvedTotalTokens =
        tokenCount > 0 ? tokenCount : (inputTokens + outputTokens);

    return AiResponse(
      requestId: requestId,
      modelUsed: modelUsed,
      capability: capability,
      responseTimeMs: responseTimeMs,
      text: text,
      inputTokens: inputTokens,
      outputTokens: outputTokens,
      tokenCount: resolvedTotalTokens,
      finishReason: finishReason,
      responseId: responseId,
    );
  }

  /// Alias for text-based analysis responses (imageUnderstanding, pdfParsing).
  /// Forwards directly to [AiResponse.text].
  factory AiResponse.analysis({
    required String requestId,
    required AiProviderId modelUsed,
    required AiCapability capability,
    required int responseTimeMs,
    required String text,
    int inputTokens = 0,
    int outputTokens = 0,
    int tokenCount = 0,
    String? finishReason = 'Fail',
    String? responseId,
  }) {
    return AiResponse.text(
      requestId: requestId,
      modelUsed: modelUsed,
      capability: capability,
      responseTimeMs: responseTimeMs,
      text: text,
      inputTokens: inputTokens,
      outputTokens: outputTokens,
      tokenCount: tokenCount,
      finishReason: finishReason,
      responseId: responseId,
    );
  }

  /// Creates an image generation response.
  ///
  /// Token Flow:
  /// Image generation endpoints (e.g. OpenAI DALL-E) do not always return raw token counts.
  /// When token counts are 0, standard pricing pseudo-tokens (35 input, 252 output per generated image)
  /// are calculated so usage accounting and budget tracking function predictably.
  factory AiResponse.image({
    required String requestId,
    required AiProviderId modelUsed,
    required int responseTimeMs,
    String? imageBase64,
    List<String>? imagesBase64,
    List<String>? generatedImages,
    int inputTokens = 0,
    int outputTokens = 0,
    int tokenCount = 0,
    String? finishReason = 'STOP',
    String? responseId,
  }) {
    // 1. Resolve image list from any provided parameter format
    final List<String> resolvedImages = imagesBase64 ??
        (imageBase64 != null ? [imageBase64] : (generatedImages ?? const []));

    // 2. Compute token metrics or assign image generation pseudo-tokens
    final imageCount = resolvedImages.length;
    final int finalInputTokens =
        inputTokens > 0 ? inputTokens : (35 * imageCount);
    final int finalOutputTokens =
        outputTokens > 0 ? outputTokens : (252 * imageCount);
    final int finalTotalTokens =
        tokenCount > 0 ? tokenCount : (finalInputTokens + finalOutputTokens);

    return AiResponse(
      requestId: requestId,
      modelUsed: modelUsed,
      capability: AiCapability.imageGeneration,
      responseTimeMs: responseTimeMs,
      generatedImages: resolvedImages,
      inputTokens: finalInputTokens,
      outputTokens: finalOutputTokens,
      tokenCount: finalTotalTokens,
      finishReason: finishReason,
      responseId: responseId,
    );
  }

  /// Backward compatibility alias forwarding to [AiResponse.image].
  factory AiResponse.imageBase64({
    required String requestId,
    required AiProviderId modelUsed,
    required int responseTimeMs,
    required String imageBase64,
    int inputTokens = 0,
    int outputTokens = 0,
    int tokenCount = 0,
    String? finishReason = 'STOP',
    String? responseId,
  }) =>
      AiResponse.image(
        requestId: requestId,
        modelUsed: modelUsed,
        responseTimeMs: responseTimeMs,
        imageBase64: imageBase64,
        inputTokens: inputTokens,
        outputTokens: outputTokens,
        tokenCount: tokenCount,
        finishReason: finishReason,
        responseId: responseId,
      );

  // ── Convenience Getters ────────────────────────────────────────────────────

  /// Base64 string of the primary generated image (if any).
  String? get imageBase64 => generatedImages?.firstOrNull;

  /// Base64 strings of all generated images (if any).
  List<String>? get imagesBase64 => generatedImages;

  /// Whether this response contains non-empty displayable text.
  bool get hasText => text != null && text!.trim().isNotEmpty;

  /// Whether this response contains at least one generated image.
  bool get hasImage =>
      generatedImages != null &&
      generatedImages!.isNotEmpty &&
      generatedImages!.first.isNotEmpty;

  @override
  String toString() =>
      'AiResponse(model: ${modelUsed.id}, capability: ${capability.id}, '
      'responseTimeMs: $responseTimeMs, tokens: $tokenCount)';
}
