import 'dart:io';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:open_filex/open_filex.dart';
import '../../features/chat/domain/message_model.dart';

/// Service responsible for:
/// 1. Compiling structured AI Markdown responses into high-quality binary PDF bytes.
/// 2. Saving generated PDFs natively to Android / iOS device directories.
/// 3. Opening generated PDFs in the device's default system viewer via [OpenFilex].
class PdfDocumentService {
  PdfDocumentService._();
  static final PdfDocumentService instance = PdfDocumentService._();

  /// Compiles a structured markdown string into publication-ready PDF bytes.
  Future<Uint8List> compileMarkdownToPdf({
    required String title,
    required String markdownContent,
  }) async {
    final pdf = pw.Document(
      title: title,
      author: 'AI Voice Genie',
      creator: 'AI Voice Genie Mobile',
    );

    final cleanLines = markdownContent.split('\n');
    final widgets = <pw.Widget>[];

    // Document Header
    widgets.add(
      pw.Header(
        level: 0,
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              title,
              style: const pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blueGrey900,
              ),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Generated by AI Voice Genie | ${DateTime.now().toLocal().toString().split(' ').first}',
              style: const pw.TextStyle(
                fontSize: 9,
                color: PdfColors.grey600,
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Divider(thickness: 1.5, color: PdfColors.blueGrey400),
            pw.SizedBox(height: 12),
          ],
        ),
      ),
    );

    // Parse Markdown lines into PDF widgets (headings, bullet points, tables, body text)
    int i = 0;
    while (i < cleanLines.length) {
      final line = cleanLines[i].trim();

      if (line.isEmpty) {
        widgets.add(pw.SizedBox(height: 6));
        i++;
        continue;
      }

      // Check if it's the start of a Markdown table
      if (line.startsWith('|') && line.endsWith('|')) {
        final tableLines = <String>[];
        while (i < cleanLines.length &&
            cleanLines[i].trim().startsWith('|') &&
            cleanLines[i].trim().endsWith('|')) {
          tableLines.add(cleanLines[i].trim());
          i++;
        }
        final tableWidget = _buildTableWidget(tableLines);
        if (tableWidget != null) {
          widgets.add(tableWidget);
          widgets.add(pw.SizedBox(height: 10));
        }
        continue;
      }

      // Check if it's a code block (``` or ~~~)
      if (line.startsWith('```') || line.startsWith('~~~')) {
        i++; // skip opening delimiter
        final codeLines = <String>[];
        while (i < cleanLines.length &&
            !cleanLines[i].trim().startsWith('```') &&
            !cleanLines[i].trim().startsWith('~~~')) {
          final rawCodeLine = cleanLines[i];
          // Strip box-drawing lines that Helvetica cannot render
          final stripped = rawCodeLine
              .replaceAll(
                  RegExp(r'[\u2500-\u257F\u2580-\u259F\u25A0-\u25FF]'), '')
              .trim();
          if (stripped.isNotEmpty) {
            codeLines.add(stripped);
          }
          i++;
        }
        if (i < cleanLines.length) i++; // skip closing delimiter

        if (codeLines.isNotEmpty) {
          widgets.add(
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(8),
              margin: const pw.EdgeInsets.symmetric(vertical: 4),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(4),
                border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
              ),
              child: pw.Text(
                codeLines.join('\n'),
                style: const pw.TextStyle(
                  fontSize: 8.5,
                  lineSpacing: 1.3,
                  color: PdfColors.blueGrey900,
                ),
              ),
            ),
          );
        }
        continue;
      }

      // Check if it's a blockquote or callout box (> ...)
      if (line.startsWith('>')) {
        final quoteLines = <String>[];
        while (i < cleanLines.length && cleanLines[i].trim().startsWith('>')) {
          var qLine = cleanLines[i].trim().substring(1).trim();
          // Remove inner heading markers like > ### Key Takeaway
          qLine = qLine.replaceFirst(RegExp(r'^#+\s*'), '');
          final cleaned = _cleanMarkdownFormatting(qLine);
          if (cleaned.isNotEmpty) {
            quoteLines.add(cleaned);
          }
          i++;
        }

        if (quoteLines.isNotEmpty) {
          widgets.add(
            pw.Container(
              width: double.infinity,
              margin: const pw.EdgeInsets.symmetric(vertical: 6),
              padding:
                  const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 8),
              decoration: const pw.BoxDecoration(
                color: PdfColors.blueGrey50,
                border: pw.Border(
                  left: pw.BorderSide(color: PdfColors.blueGrey700, width: 3.5),
                ),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: quoteLines.map((ql) {
                  return pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 2),
                    child: pw.Text(
                      ql,
                      style: const pw.TextStyle(
                        fontSize: 9.5,
                        fontStyle: pw.FontStyle.italic,
                        color: PdfColors.blueGrey900,
                        lineSpacing: 1.4,
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
          );
        }
        continue;
      }

      // Headings
      if (line.startsWith('# ')) {
        // Skip document main title if it matches the header title
        final headingText = _cleanMarkdownFormatting(line.substring(2));
        if (headingText != title) {
          widgets.add(pw.SizedBox(height: 12));
          widgets.add(
            pw.Text(
              headingText,
              style: const pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blueGrey900,
              ),
            ),
          );
          widgets.add(pw.SizedBox(height: 6));
        }
      } else if (line.startsWith('## ')) {
        widgets.add(pw.SizedBox(height: 10));
        widgets.add(
          pw.Text(
            _cleanMarkdownFormatting(line.substring(3)),
            style: const pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blueGrey800,
            ),
          ),
        );
        widgets.add(pw.SizedBox(height: 4));
      } else if (line.startsWith('### ')) {
        widgets.add(pw.SizedBox(height: 8));
        widgets.add(
          pw.Text(
            _cleanMarkdownFormatting(line.substring(4)),
            style: const pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blueGrey700,
            ),
          ),
        );
        widgets.add(pw.SizedBox(height: 4));
      } else if (line.startsWith('* ') ||
          line.startsWith('- ') ||
          line.startsWith('• ')) {
        // Bullet list item
        final rawText = line.substring(2).trim();
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 8, bottom: 4),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  width: 3.5,
                  height: 3.5,
                  margin: const pw.EdgeInsets.only(top: 4, right: 6),
                  decoration: const pw.BoxDecoration(
                    color: PdfColors.blueGrey800,
                    shape: pw.BoxShape.circle,
                  ),
                ),
                pw.Expanded(
                  child: pw.Text(
                    _cleanMarkdownFormatting(rawText),
                    style: const pw.TextStyle(fontSize: 10, lineSpacing: 1.5),
                  ),
                ),
              ],
            ),
          ),
        );
      } else if (RegExp(r'^\d+\.\s').hasMatch(line)) {
        // Numbered list item
        final match = RegExp(r'^(\d+\.)\s*(.*)$').firstMatch(line);
        final prefix = match?.group(1) ?? '-';
        final rawText = match?.group(2) ?? line;
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 8, bottom: 4),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('$prefix ',
                    style: const pw.TextStyle(
                        fontWeight: pw.FontWeight.bold, fontSize: 10)),
                pw.Expanded(
                  child: pw.Text(
                    _cleanMarkdownFormatting(rawText),
                    style: const pw.TextStyle(fontSize: 10, lineSpacing: 1.5),
                  ),
                ),
              ],
            ),
          ),
        );
      } else if (line.startsWith('---') || line.startsWith('___')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 8),
          child: pw.Divider(color: PdfColors.grey300, thickness: 0.8),
        ));
      } else {
        // Standard body paragraph
        final cleanedBody = _cleanMarkdownFormatting(line);
        if (cleanedBody.isNotEmpty) {
          widgets.add(
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 6),
              child: pw.Text(
                cleanedBody,
                style: const pw.TextStyle(
                  fontSize: 10,
                  lineSpacing: 1.8,
                  color: PdfColors.blueGrey900,
                ),
              ),
            ),
          );
        }
      }

      i++;
    }

    // Add multi-page layout with headers, footers, and page numbers
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(top: 10),
            child: pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
            ),
          );
        },
        build: (pw.Context context) => widgets,
      ),
    );

    return await pdf.save();
  }

  /// Parses table markdown lines into a formatted [pw.Table].
  pw.Widget? _buildTableWidget(List<String> lines) {
    if (lines.length < 2) return null;

    final rows = <pw.TableRow>[];
    bool isHeader = true;

    for (final line in lines) {
      // Skip separator lines like |---|---| or |:---|:---|
      if (RegExp(r'^\|?(\s*:?-+:?\s*\|)+\s*$').hasMatch(line) ||
          line.contains('---')) {
        isHeader = false;
        continue;
      }

      final cells = line
          .split('|')
          .map((c) => c.trim())
          .where((c) => c.isNotEmpty)
          .toList();

      if (cells.isEmpty) continue;

      rows.add(
        pw.TableRow(
          decoration: isHeader
              ? const pw.BoxDecoration(color: PdfColors.blueGrey50)
              : null,
          children: cells.map((cellText) {
            return pw.Padding(
              padding:
                  const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
              child: pw.Text(
                _cleanMarkdownFormatting(cellText),
                style: pw.TextStyle(
                  fontSize: 8.5,
                  fontWeight:
                      isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
                  color:
                      isHeader ? PdfColors.blueGrey900 : PdfColors.blueGrey800,
                  lineSpacing: 1.2,
                ),
              ),
            );
          }).toList(),
        ),
      );

      isHeader = false;
    }

    if (rows.isEmpty) return null;

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      children: rows,
    );
  }

  /// Strips formatting markers (bold **, italic *, code `) and sanitizes URLs & glyphs for PDF rendering
  static String _cleanMarkdownFormatting(String raw) {
    return raw
        // Fix Dart replaceAll backreference bug by using replaceAllMapped
        .replaceAllMapped(RegExp(r'\*\*(.*?)\*\*'), (m) => m[1] ?? '')
        .replaceAllMapped(RegExp(r'\*(.*?)\*'), (m) => m[1] ?? '')
        .replaceAllMapped(RegExp(r'`(.*?)`'), (m) => m[1] ?? '')
        // Clean markdown links [Title](url) -> if url is long/redirect, show only Title
        .replaceAllMapped(RegExp(r'\[([^\]]+)\]\(([^)]+)\)'), (m) {
          final label = m[1] ?? '';
          final url = m[2] ?? '';
          if (url.contains('grounding-api-redirect') ||
              url.contains('vertexaisearch') ||
              url.length > 80) {
            return label;
          }
          return '$label ($url)';
        })
        // Strip Unicode box-drawing characters and pseudo-borders (causes ☒ boxes in Helvetica)
        .replaceAll(RegExp(r'[\u2500-\u257F\u2580-\u259F\u25A0-\u25FF]'), '')
        .trim();
  }

  /// Extracts a human-friendly document title from the markdown text or user prompt.
  static String extractDocumentTitle(String prompt, String content) {
    final lines = content.split('\n');

    // 1. Look for first Markdown # Heading in markdown content (allow up to 120 chars)
    for (final line in lines) {
      final trimmed = line.trim();
      if (trimmed.startsWith('# ')) {
        final heading = trimmed
            .replaceFirst(RegExp(r'^#+\s*'), '')
            .replaceAll('*', '')
            .trim();
        if (heading.isNotEmpty && heading.length <= 120) {
          return heading;
        }
      }
    }

    // 2. Check for first Bold Heading line: e.g. **Architectural Analysis: ...**
    for (final line in lines) {
      final trimmed = line.trim();
      if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
        final heading = trimmed.replaceAll('*', '').trim();
        if (heading.isNotEmpty && heading.length <= 120) {
          return heading;
        }
      }
    }

    // 3. Derive from user prompt: e.g. "Generate the pdf, in which describes the comparison of Generative AI, Agent AI, Agentic AI"
    String cleanPrompt = prompt
        .replaceAll(
          RegExp(
            r'^(can you|please|could you|i want to|i need to)?\s*(generate|create|make|write|export)\s*(the|a)?\s*(pdf|document|report)?\s*',
            caseSensitive: false,
          ),
          '',
        )
        .trim();

    // Clean conversational clauses like "in which describes the", "describing the", "about", etc.
    cleanPrompt = cleanPrompt
        .replaceAll(
          RegExp(
            r'^[,\s]*(in which describes|which describes|which compares|describing|comparing|about|on|for|of)?\s*(the|a|an)?\s*',
            caseSensitive: false,
          ),
          '',
        )
        .trim();

    // Remove trailing punctuation
    cleanPrompt = cleanPrompt.replaceAll(RegExp(r'[.,;?!]+$'), '').trim();

    if (cleanPrompt.isNotEmpty) {
      final wordsList = cleanPrompt.split(RegExp(r'\s+'));
      final words =
          (wordsList.length <= 10 ? wordsList : wordsList.take(8)).join(' ');
      final trimmedWords = words.replaceAll(RegExp(r'[,;:]+$'), '').trim();
      if (trimmedWords.isNotEmpty) {
        return trimmedWords[0].toUpperCase() + trimmedWords.substring(1);
      }
    }

    return 'AI_Generated_Document';
  }

  /// Formats a document title into a concise, filesystem-safe filename (20-35 chars, max 5 words).
  /// Strips colons/dashes and subtitles to ensure names fit elegantly in mobile cards and snackbars.
  static String formatFileName(String docTitle) {
    var title = docTitle.trim();

    // If title has a colon or dash subtitle, use the concise main topic
    if (title.contains(':')) {
      final firstPart = title.split(':').first.trim();
      if (firstPart.split(RegExp(r'\s+')).length >= 2 &&
          firstPart.length >= 6) {
        title = firstPart;
      }
    } else if (title.contains(' — ') || title.contains(' - ')) {
      final sep = title.contains(' — ') ? ' — ' : ' - ';
      final firstPart = title.split(sep).first.trim();
      if (firstPart.split(RegExp(r'\s+')).length >= 2 &&
          firstPart.length >= 6) {
        title = firstPart;
      }
    }

    // Sanitize non-alphanumeric characters (keep alphanumeric and hyphens)
    final sanitized = title.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
    final words =
        sanitized.split(RegExp(r'\s+')).where((w) => w.isNotEmpty).toList();

    // Accumulate whole words up to 5 words and ~35 chars without chopping words mid-way
    final selectedWords = <String>[];
    int currentLength = 0;
    for (final word in words) {
      if (selectedWords.length >= 5) break;
      final int addition =
          selectedWords.isEmpty ? word.length : word.length + 1;
      if (currentLength + addition > 36 && selectedWords.isNotEmpty) {
        break;
      }
      selectedWords.add(word);
      currentLength += addition;
    }

    if (selectedWords.isEmpty) return 'AI_Document.pdf';

    final joined = selectedWords.join('_');
    return '$joined.pdf';
  }

  /// Saves PDF bytes locally to the app's internal documents directory.
  /// This guarantees 100% success on all Android and iOS versions without permissions,
  /// and allows OpenFilex to create a FileProvider content URI with read permissions.
  Future<String?> savePdfLocally({
    required Uint8List bytes,
    required String fileName,
  }) async {
    try {
      final safeName = fileName.endsWith('.pdf') ? fileName : '$fileName.pdf';
      final docsDir = await getApplicationDocumentsDirectory();
      final targetDir = Directory('${docsDir.path}/generated_pdfs');
      if (!await targetDir.exists()) {
        await targetDir.create(recursive: true);
      }

      final filePath = '${targetDir.path}/$safeName';
      final file = File(filePath);
      await file.writeAsBytes(bytes, flush: true);

      debugPrint(
          '📄 PdfDocumentService: Cached PDF locally at $filePath (${bytes.length} bytes)');
      return filePath;
    } catch (e) {
      debugPrint('⚠️ PdfDocumentService.savePdfLocally error: $e');
      return null;
    }
  }

  /// Backward-compatible alias for [savePdfLocally].
  Future<String?> savePdfToDevice({
    required Uint8List bytes,
    required String fileName,
  }) =>
      savePdfLocally(bytes: bytes, fileName: fileName);

  /// Resolves the bytes of a PDF attachment, checking internal cache first,
  /// then existing valid local file, then authenticated Cloud Storage, and finally HTTP GET.
  Future<Uint8List?> resolvePdfBytes(PdfAttachmentInfo pdfInfo) async {
    final safeName =
        pdfInfo.name.endsWith('.pdf') ? pdfInfo.name : '${pdfInfo.name}.pdf';

    // 1. Check if already cached in app's internal documents directory
    try {
      final docsDir = await getApplicationDocumentsDirectory();
      final cachedFile = File('${docsDir.path}/generated_pdfs/$safeName');
      if (await cachedFile.exists() && await cachedFile.length() > 0) {
        debugPrint(
            '📄 PdfDocumentService: Found cached PDF at ${cachedFile.path}');
        return await cachedFile.readAsBytes();
      }
    } catch (e) {
      debugPrint('ℹ️ Internal cache check notice: $e');
    }

    // 2. Try reading existing valid local file path (safely wrapped in try-catch)
    if (pdfInfo.path.isNotEmpty) {
      try {
        final cleanPath = pdfInfo.path.replaceFirst('file://', '');
        // Do not attempt to read from raw Android public paths without Scoped Storage permission
        if (!cleanPath.startsWith('/storage/emulated/0/Download')) {
          final file = File(cleanPath);
          if (await file.exists() && await file.length() > 0) {
            final bytes = await file.readAsBytes();
            await savePdfLocally(bytes: bytes, fileName: safeName);
            return bytes;
          }
        }
      } catch (e) {
        debugPrint('ℹ️ Local path not accessible: $e');
      }
    }

    // 3. Fetch from Cloud Storage
    final url = pdfInfo.url;
    if (url != null && url.isNotEmpty) {
      // 3a. Use FirebaseStorage SDK (handles auth session and storage rules seamlessly)
      try {
        if (url.contains('firebasestorage.googleapis.com')) {
          final ref = FirebaseStorage.instance.refFromURL(url);
          final bytes = await ref.getData(25 * 1024 * 1024); // max 25MB
          if (bytes != null && bytes.isNotEmpty) {
            await savePdfLocally(bytes: bytes, fileName: safeName);
            debugPrint(
                '☁️ PdfDocumentService: Downloaded PDF via FirebaseStorage SDK');
            return bytes;
          }
        }
      } catch (e) {
        debugPrint('ℹ️ FirebaseStorage.refFromURL getData notice: $e');
      }

      // 3b. Fall back to direct HTTP GET
      try {
        final response =
            await http.get(Uri.parse(url)).timeout(const Duration(seconds: 20));
        if (response.statusCode == 200 && response.bodyBytes.isNotEmpty) {
          await savePdfLocally(bytes: response.bodyBytes, fileName: safeName);
          debugPrint('☁️ PdfDocumentService: Downloaded PDF via HTTP GET');
          return response.bodyBytes;
        }
      } catch (e) {
        debugPrint('⚠️ HTTP download failed: $e');
      }
    }

    return null;
  }

  /// Saves the PDF to the device's public Downloads directory (Android)
  /// or Application Documents (iOS), making it visible to the user's file manager.
  Future<bool> savePdfToPublicDownloads({
    required Uint8List bytes,
    required String fileName,
  }) async {
    final safeName = fileName.endsWith('.pdf') ? fileName : '$fileName.pdf';
    try {
      if (Platform.isAndroid) {
        // 1. Try native MediaStore download insert via MethodChannel
        try {
          const channel = MethodChannel('com.voicegenie.app/image_save');
          final result = await channel.invokeMethod<Map>('saveDocumentBytes', {
            'bytes': bytes,
            'fileName': safeName,
            'mimeType': 'application/pdf',
          });
          final success = result?['success'] as bool? ?? false;
          if (success) {
            debugPrint('📄 PdfDocumentService: Saved via MediaStore Downloads');
            return true;
          }
        } catch (e) {
          debugPrint(
              'ℹ️ Native MediaStore channel failed or not yet recompiled: $e');
        }

        // 2. Resilient fallback: Save to app-specific external storage downloads folder
        try {
          final extDirs = await getExternalStorageDirectories(
              type: StorageDirectory.downloads);
          if (extDirs != null && extDirs.isNotEmpty) {
            final targetDir = extDirs.first;
            final file = File('${targetDir.path}/$safeName');
            await file.writeAsBytes(bytes, flush: true);
            debugPrint(
                '📄 PdfDocumentService: Saved to external storage at ${file.path}');
            return true;
          }
        } catch (e) {
          debugPrint('ℹ️ External storage fallback failed: $e');
        }

        return false;
      } else {
        // iOS: Application Documents Directory (visible in iOS Files app)
        final docsDir = await getApplicationDocumentsDirectory();
        final file = File('${docsDir.path}/$safeName');
        await file.writeAsBytes(bytes, flush: true);
        return true;
      }
    } catch (e) {
      debugPrint('⚠️ PdfDocumentService.savePdfToPublicDownloads error: $e');
      return false;
    }
  }

  /// Opens the PDF file with the native system viewer.
  /// Guarantees that the file exists locally before invoking OpenFilex.
  Future<OpenResult> openPdf(PdfAttachmentInfo pdfInfo) async {
    try {
      final safeName =
          pdfInfo.name.endsWith('.pdf') ? pdfInfo.name : '${pdfInfo.name}.pdf';
      final docsDir = await getApplicationDocumentsDirectory();
      final cachedFile = File('${docsDir.path}/generated_pdfs/$safeName');

      // 1. If cached locally and non-empty, open immediately!
      if (await cachedFile.exists() && await cachedFile.length() > 0) {
        debugPrint(
            '📄 PdfDocumentService.openPdf: Opening cached file at ${cachedFile.path}');
        return await OpenFilex.open(cachedFile.path, type: 'application/pdf');
      }

      // 2. Otherwise resolve bytes and cache them
      final bytes = await resolvePdfBytes(pdfInfo);
      if (bytes != null && bytes.isNotEmpty) {
        final localPath =
            await savePdfLocally(bytes: bytes, fileName: safeName);
        if (localPath != null) {
          debugPrint(
              '📄 PdfDocumentService.openPdf: Opening newly cached file at $localPath');
          return await OpenFilex.open(localPath, type: 'application/pdf');
        }
      }

      return OpenResult(
        type: ResultType.fileNotFound,
        message: 'File not found locally or remotely',
      );
    } catch (e) {
      debugPrint('⚠️ PdfDocumentService.openPdf error: $e');
      return OpenResult(type: ResultType.error, message: e.toString());
    }
  }

  /// Opens the PDF file directly with the system viewer.
  Future<void> openPdfFile(String filePath) async {
    try {
      await OpenFilex.open(filePath, type: 'application/pdf');
    } catch (e) {
      debugPrint('⚠️ PdfDocumentService.openPdfFile error: $e');
    }
  }
}
