import 'dart:ui';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';

import 'core/constants/app_colors.dart';
import 'core/error/effect_listener.dart';
import 'core/localization/app_localizations.dart';
import 'core/localization/locale_provider.dart';
import 'core/router/app_routes.dart';
import 'core/services/analytics_service.dart';
import 'core/services/storage_service.dart';
import 'core/theme/app_theme.dart';
import 'core/theme/theme_provider.dart';
import 'features/auth/presentation/auth_provider.dart';
import 'features/key_setup/presentation/api_key_provider.dart';

// Firebase options — generated by FlutterFire CLI in Phase 1
import 'firebase_options.dart';

// =============================================================================
// ENTRY POINT
// =============================================================================

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Firebase ────────────────────────────────────────────────────────────────
  // Uncomment after running: flutterfire configure
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // ── Crashlytics ─────────────────────────────────────────────────────────────
  // Pass all uncaught "fatal" errors from the framework to Crashlytics
  FlutterError.onError = (errorDetails) {
    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };

  // Pass all uncaught asynchronous errors that aren't handled by the Flutter framework to Crashlytics
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  // ── Local Storage ───────────────────────────────────────────────────────────
  // Hive must be initialized before any provider reads storage
  await StorageService().initialize();

  // ── System UI ────────────────────────────────────────────────────────────────
  // Status bar is transparent — AppBar background shows through
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      statusBarBrightness: Brightness.light,
      systemNavigationBarColor: AppColors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  // ── Orientation ───────────────────────────────────────────────────────────────
  // Lock to portrait only (portrait-up and portrait-down)
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  runApp(const AiVoiceGenieApp());
}

// =============================================================================
// ROOT APP WIDGET
// =============================================================================

class AiVoiceGenieApp extends StatelessWidget {
  const AiVoiceGenieApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: _buildProviders(),
      child: Consumer2<ThemeProvider, LocaleProvider>(
        builder: (context, themeProvider, localeProvider, _) {
          return MaterialApp(
            // ── App Config ────────────────────────────────────────────────────
            debugShowCheckedModeBanner: false,

            // ── Theme ─────────────────────────────────────────────────────────
            // Both themes are always defined — toggled via ThemeProvider
            theme: AppTheme.getLightTheme(context),
            darkTheme: AppTheme.getDarkTheme(context),
            themeMode: themeProvider.themeMode,

            // ── Localization ───────────────────────────────────────────────────
            locale: localeProvider.locale,
            supportedLocales: LocaleProvider.supportedLocales,
            localizationsDelegates: const [
              AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],

            // ── Routing ────────────────────────────────────────────────────────
            // All navigation goes through AppRoutes.generateRoute
            onGenerateRoute: AppRoutes.generateRoute,
            initialRoute: AppRoutes.splash,
            navigatorObservers: [
              AnalyticsService.instance.getAnalyticsObserver(),
            ],

            // ── Global Builder ─────────────────────────────────────────────────
            // Wraps the entire Navigator tree with:
            //   1. Responsive text scaling (phone / tablet adaptive)
            //   2. GlobalEffectListener (catches all EffectBus failures)
            builder: (context, child) {
              final mediaQueryData = MediaQuery.of(context);
              final screenWidth = mediaQueryData.size.width;

              // Text scale factor adapts to device size
              final double textScaleFactor = _resolveTextScaleFactor(screenWidth);

              return MediaQuery(
                data: mediaQueryData.copyWith(
                  textScaler: TextScaler.linear(textScaleFactor),
                ),
                // GlobalEffectListener catches all EffectBus emissions and
                // shows them as warning messages via MessageUtils
                child: GlobalEffectListener(child: child!),
              );
            },
          );
        },
      ),
    );
  }

  // ── Provider Registration ───────────────────────────────────────────────────

  /// All root-level providers for the app.
  ///
  /// Providers are listed in dependency order:
  ///   1. Theme + Locale (no dependencies — initialize from storage)
  ///   2. Auth (depends on storage being ready)
  ///   3. Feature providers (depend on auth being ready)
  List<ChangeNotifierProvider> _buildProviders() {
    return [
      // ── Core Providers ────────────────────────────────────────────────────
      ChangeNotifierProvider<ThemeProvider>(
        create: (_) => ThemeProvider()..initialize(),
      ),
      ChangeNotifierProvider<LocaleProvider>(
        create: (_) => LocaleProvider()..initialize(),
      ),

      // ── Feature providers will be added in subsequent phases ──────────────
      // Phase 1: AuthProvider — lazy: false so auth resolves before splash ends
      ChangeNotifierProvider<AuthProvider>(
        create: (_) => AuthProvider()..initialize(),
        lazy: false,
      ),
      // Phase 2: ApiKeyProvider
      ChangeNotifierProvider<ApiKeyProvider>(create: (_) => ApiKeyProvider()),
      // Phase 4: ChatProvider
      // ChangeNotifierProvider(create: (_) => ChatProvider()),
      // Phase 3: ApiKeyProvider
      // Phase 4: ChatProvider
      // Phase 5: ImageGeneratorProvider
      // Phase 6: PdfReaderProvider
      // Phase 7: ConversationHistoryProvider
      // Phase 8: SettingsProvider
    ];
  }

  // ── Text Scale Factor ───────────────────────────────────────────────────────

  /// Resolve responsive text scaling based on device screen width.
  ///
  /// This ensures text is readable on all device sizes without relying
  /// on the OS text scaling (which users may set to very large values).
  double _resolveTextScaleFactor(double screenWidth) {
    if (screenWidth >= 600) {
      // Tablet — slightly larger for better readability on big screens
      return 1.1;
    } else if (screenWidth <= 360) {
      // Small phone (e.g. old Android devices)
      return 0.85;
    }
    // Standard phone
    return 1.0;
  }
}